"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: rohand
  IDL file: hand_interface.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# # root module import for resolving types
# import core

class ROHandCtrlMode(idl.IdlEnum, typename="rohand.ROHandCtrlMode", default="HAND_MODE_POSITION"):
    HAND_MODE_POSITION = auto()
    HAND_MODE_ANGLE = auto()

@dataclass
@annotate.final
@annotate.autoid("sequential")
class ROHandCtrl(idl.IdlStruct, typename="core.ROHandCtrl"):
    finger_id: types.uint8
    target_value: types.uint16
    speed: types.uint8
    mode: ROHandCtrlMode


